### ISSUE TITLE
overflow: auto; for search results

### ISSUE THREAD

**Issue by laufhannes** [Runalyze/Runalyze#1591]
See related #1427. Just add the following line to our css:
```css
#searchResult {
    overflow: auto;
}
```

The overlay itself has only `overflow: auto;` for a screen width below 1024px, otherwise the close icon won't show up nicely.
