### ISSUE TITLE
Doctrine Cache

### ISSUE THREAD

**Issue by mipapo** [Runalyze/Runalyze#1900]
Doctrine has an own caching system.
Most people use APC for doctrine caching.
Problem: APC is often not available at shared hosting
The problem is that this would require to have php-apc installed (when we would configure it in our `config.yml`). Otherwise doctrine would throw an exception.
If we exclude it from the `config.yml` it could be added to `data/config.yml` 

```
doctrine:
    orm:
        query_cache_driver: apc
        metadata_cache_driver: apc
        result_cache_driver: apc
```
Users could put this at the end of the `data/config.yml` file. 
I really don't know if we could require that users have php-apc installed...
